# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 03:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ExamCreation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterAllocated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RequestConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestdate', models.DateField(auto_now_add=True)),
                ('examname', models.CharField(max_length=500, unique=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('admitid', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('requestdate',),
            },
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('admitid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('requestdatetime', models.DateTimeField(auto_now=True)),
                ('allocated', models.BooleanField(default=False)),
                ('is_handicap', models.BooleanField(default=False)),
                ('is_female', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slotid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamCreation.ExamSlot')),
            ],
            options={
                'ordering': ('is_handicap', 'is_female', 'requestdatetime'),
            },
        ),
        migrations.AddField(
            model_name='centerallocated',
            name='admitno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admitno', to='UserRegistration.StudentRequest'),
        ),
        migrations.AddField(
            model_name='centerallocated',
            name='centerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centerid', to='ExamCreation.Center'),
        ),
        migrations.AddField(
            model_name='centerallocated',
            name='examname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examname', to='ExamCreation.Exam'),
        ),
    ]
