# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capicity', models.IntegerField()),
            ],
            options={
                'ordering': ('state', 'city'),
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('registrationStartDate', models.DateTimeField()),
                ('registrationEndDate', models.DateTimeField()),
                ('days', models.IntegerField()),
                ('slots', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exam', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ExamSlot',
            fields=[
                ('Slotid', models.TextField(max_length=1000, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('centerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamCreation.Center')),
                ('examid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamCreation.Exam')),
            ],
        ),
        migrations.AddField(
            model_name='center',
            name='examid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamCreation.Exam'),
        ),
    ]
